PBIoT.GUI/Controllers/GraficarVariablesController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using PBIoT.GUI.Models;

namespace PBIoT.GUI.Controllers
{
    public class GraficarVariablesController : Controller
    {
        // GET: GraficarVariables
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult usp_ObtenerGreaficaVariablesXMinuto(string fecha)
        {
            try
            {
                using (var DB = new PBIoTDBEntities())
                {

                    Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US");

                    // var viewModel = new List<usp_ObtenerReportePromedioEjecucion_Result>();
                    var viewModel = new List<uspObtenerVariablePLCGraficaXMinuto_Result>();
                    var resultado = DB.uspObtenerVariablePLCGraficaXMinuto(Convert.ToDateTime(fecha)).ToList();
                    foreach (var resultadoItem in resultado)
                    {
                        viewModel.Add(resultadoItem);
                    }

                    return Json(viewModel);

                }
            }

            catch (Exception ex)
            {
                return new HttpStatusCodeResult(550, "Some error" + ex.Message);
            }


        }
            


    }
}

PBIoT.GUI/Controllers/ParoController.cs
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using PBIoT.GUI.Models;

namespace PBIoT.GUI.Controllers
{
    public class ParoController : Controller
    {
        // GET: Paro
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ObtenerParosXDia([DataSourceRequest]DataSourceRequest request, string fecha)
        {
            try
            {
                using (var DB = new PBIoTDBEntities())
                {

                    Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US");
                    // var viewModel = new List<usp_ObtenerReportePromedioEjecucion_Result>();
                    var viewModel = new List<uspObtenerInformacionParosXDia_Result>();
                    var resultado = DB.uspObtenerInformacionParosXDia(Convert.ToDateTime(fecha)).ToList();
                    foreach (var resultadoItem in resultado)
                    {
                        viewModel.Add(resultadoItem);
                    }

                    return Json(viewModel);

                }
            }


            catch (Exception ex)
            {
                return new HttpStatusCodeResult(550, "Some error" + ex.Message);
            }

        }

        public ActionResult ObtenerTop5ParosXDia([DataSourceRequest] DataSourceRequest request, string fecha)
        {
            try
            {
                using (var DB = new PBIoTDBEntities())
                {

                    Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US");

                    var resultado = DB.uspObtenerTop5ParosXDia(Convert.ToDateTime(fecha)).ToList();
                    List<Object> viewModel = new List<object>();
                    foreach (var resultadoItem in resultado)
                    {
                        viewModel.Add(new
                        {
                            Motivo = resultadoItem.Motivo,
                            Descripcion = resultadoItem.Descripcion,
                            Inicio = resultadoItem.Inicio,
                            Fin = resultadoItem.Fin,
                            TotalTiempo = resultadoItem.TotalTiempo

                        });
                    }

                    DataSourceResult result = viewModel.ToDataSourceResult(request);
                    var jsonresult = Json(result);
                    return Json(result);

                }

            }
            catch (Exception ex)
            {
                return new HttpStatusCodeResult(550, "Some error" + ex.Message);
            }

        }

    }
}

PBIoT.GUI/Controllers/ParoMotivoController.cs
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using PBIoT.GUI.Models;

namespace PBIoT.GUI.Controllers
{
    public class ParoMotivoController : Controller
    {
        // GET: ParoMotivo
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ObtenerParosMotivoXMes([DataSourceRequest] DataSourceRequest request, string fecha)
        {
            try
            {
                using (var DB = new PBIoTDBEntities())
                {

                    Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US");

                    var resultado = DB.uspObtenerParosMotivoXMes(Convert.ToDateTime(fecha)).ToList();
                    List<Object> viewModel = new List<object>();
                    foreach (var resultadoItem in resultado)
                    {
                        viewModel.Add(new
                        {
                            IdParo = resultadoItem.IdParo,
                            Motivo = resultadoItem.Motivo,
                            Descripcion = resultadoItem.Descripcion,
                            Inicio = resultadoItem.Inicio,
                            Fin = resultadoItem.Fin,
                            TotalTiempo = resultadoItem.TotalTiempo

                        });
                    }

                    DataSourceResult result = viewModel.ToDataSourceResult(request);
                    var jsonresult = Json(result);
                    return Json(result);

                }

            }
            catch (Exception ex)
            {
                return new HttpStatusCodeResult(550, "Some error" + ex.Message);
            }

        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult ActualizarParoMotivo([DataSourceRequest] DataSourceRequest request, uspObtenerParosMotivoXMes_Result paroMotivoEdit)
        {
            try
            {
                using (var DB = new PBIoTDBEntities())
                {

                    if (paroMotivoEdit != null)
                    {

                        DB.uspActualizarMotivoParo(
                            paroMotivoEdit.IdParo
                            , paroMotivoEdit.Motivo

                            );
                        //DB.Receta.Attach(referenciasEdit);
                        //DB.Entry(referenciasEdit).State = System.Data.Entity.EntityState.Modified;
                        DB.SaveChanges();
                    }

                    //return Json(new[] { paroMotivoEdit }.ToDataSourceResult(request, ModelState));
                    return Json(true, JsonRequestBehavior.AllowGet);

                }

            }
            catch (Exception ex)
            {
                return new HttpStatusCodeResult(550, "Some error" + ex.Message);
            }

        }
    }
}

PBIoT.GUI/Controllers/ParoPendienteController.cs
using Kendo.Mvc.UI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PBIoT.GUI.Models;
using Kendo.Mvc.Extensions;

namespace PBIoT.GUI.Controllers
{
    public class ParoPendienteController : Controller
    {
        // GET: ParoPendiente
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ObtenerTodosParosFinalizar([DataSourceRequest] DataSourceRequest request)
        {
            try
            {

                using (var DB = new PBIoTDBEntities())
                {


                    IQueryable<uspObtenerTodosParosPendientesFinalizar_Result> obtenerParosXFinalizar = (IQueryable<uspObtenerTodosParosPendientesFinalizar_Result>)DB.uspObtenerTodosParosPendientesFinalizar().AsQueryable();
                    DataSourceResult result = obtenerParosXFinalizar.ToList().ToDataSourceResult(request);
                    return Json(result);

                }

            }
            catch (Exception ex)
            {
                return new HttpStatusCodeResult(550, "Some error" + ex.Message);
            }

        }


        [AcceptVerbs(HttpVerbs.Post)]
        //[HttpPost]
        public ActionResult ParosPendientesFinalizar([DataSourceRequest]DataSourceRequest request)
        {
            {
                try
                {

                    using (var DB = new PBIoTDBEntities())
                    {


                        //var resultado = DB.uspObtenerParoPorFinalizar().ToList();
                        //List<Object> viewModel = new List<object>();
                        var resultado = DB.uspObtenerParoPorFinalizar().FirstOrDefault();
                        Object viewModel = new
                        {

                            IdParo = resultado.IdParo,
                            Inicio = resultado.Inicio.ToString(),
                            Fin = resultado.Fin.ToString(),


                        };

                        //DataSourceResult result = viewModel.ToDataSourceResult(request);
                        //var jsonresult = Json(result);
                        //return Json(result);
                        return Json(viewModel, JsonRequestBehavior.AllowGet);

                    }




                }

                catch (Exception ex)
                {
                    return new HttpStatusCodeResult(550, "Some error" + ex.Message);
                }

            }
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult GuardarParoPendiente([DataSourceRequest] DataSourceRequest request, string IdParo, string CodigoParo)
        {
            try
            {
                using (var DB = new PBIoTDBEntities())
                {


                    //referenciasEdit2.Id = referenciasEdit.Id;

                    DB.uspGuardarParoPendientePorFinalizar(
                        Convert.ToInt64(IdParo),
                        CodigoParo);
                    DB.SaveChanges();


                    return Json("Guardo exitosamente el paro pendiente por finalizar", JsonRequestBehavior.AllowGet);

                }
                //return Json("sisas", JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {
                //return Json("No Guardo el paro pendiente por finalizar", JsonRequestBehavior.AllowGet);
                return Content(ex.Message);
            }

        }

    }
}

PBIoT.GUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Reportes Y KPI</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
	<!--This bundle was moved by the Telerik VS Extensions for compatibility reasons-->
	@Scripts.Render("~/bundles/jquery")
	<link href="https://kendo.cdn.telerik.com/2018.1.221/styles/kendo.common.min.css" rel="stylesheet" type="text/css" />
	<link href="https://kendo.cdn.telerik.com/2018.1.221/styles/kendo.mobile.all.min.css" rel="stylesheet" type="text/css" />
	<link href="https://kendo.cdn.telerik.com/2018.1.221/styles/kendo.flat.min.css" rel="stylesheet" type="text/css" />
	<script src="https://kendo.cdn.telerik.com/2018.1.221/js/jquery.min.js"></script>
	<script src="https://kendo.cdn.telerik.com/2018.1.221/js/jszip.min.js"></script>
	<script src="https://kendo.cdn.telerik.com/2018.1.221/js/kendo.all.min.js"></script>
	<script src="https://kendo.cdn.telerik.com/2018.1.221/js/kendo.aspnetmvc.min.js"></script>
	<script src="@Url.Content("~/Scripts/kendo.modernizr.custom.js")"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Reportes y KPI", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Inicio", "Index", "Home")</li>*@
                    @*<li>@Html.ActionLink("Acerca de", "About", "Home")</li>*@
                    <li>@Html.ActionLink("Variables", "Index", "GraficarVariables")</li>
                    <li>@Html.ActionLink("OEE", "Index", "OEE")</li>
                    <li>@Html.ActionLink("Paros Pendientes", "Index", "ParoPendiente")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Tiempos Perdidos</a>
                        <ul class="dropdown-menu multi-level">
                            <li>@Html.ActionLink("Tiempos Perdidos", "Index", "Paro")</li>
                            <li>@Html.ActionLink("Paro Motivo", "Index", "ParoMotivo")</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    @*<div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year -INTECOL - PASCUAL BRAVO</p>
            </footer>
        </div>*@

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer style="text-align:center">
            <label>
                <p>&copy; @DateTime.Now.Year -INTECOL - PASCUAL BRAVO</p>
            </label>
            @*<img width="120" height="120" src="~/Image/LOGO.jpg" style="padding:10px 10px 10px 10px" />*@
        </footer>
    </div>


    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>